[package]
name = "baf_bin"
version = "0.1.3"
edition = "2024"

[[bin]]
name = "baf"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
baf = { path = "../crate-lib" }
clap = { version = "4.6.5", features = ["derive"] }
colored = "3.1.1"
jiff = "0.2.35"
log = { version = "0.4.33", features = ["std"] }
walkdir = "2.5.0"
zip = "8.6.0"
